name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: docker build --file Dockerfile --tag amiras98/final-python:${{ github.run_number }}-${{ github.sha }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.MY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.MY_DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Registry
        run: docker push amiras98/final-python:${{ github.run_number }}-${{ github.sha }}
